"use client";

import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { ScanRecord, Verdict } from "@/app/dashboard/scan-types";
import { CATEGORY_LABELS, VERDICT_LABELS } from "@/app/dashboard/scan-types";
import { useState } from "react";

const RISK_COLORS: Record<string, string> = {
  low: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300",
  medium: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
  high: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300",
  critical: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300",
};

const SEVERITY_COLORS: Record<string, string> = {
  low: "bg-neutral-100 text-neutral-700 border-neutral-200 dark:bg-neutral-800 dark:text-neutral-300 dark:border-neutral-700",
  medium: "bg-amber-50 text-amber-800 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800",
  high: "bg-orange-50 text-orange-800 border-orange-200 dark:bg-orange-950/40 dark:text-orange-300 dark:border-orange-800",
  critical: "bg-red-50 text-red-800 border-red-200 dark:bg-red-950/40 dark:text-red-300 dark:border-red-800",
};

const VERDICT_STYLES: Record<Verdict, { container: string; text: string }> = {
  safe: {
    container: "border-emerald-200 bg-emerald-50/70 dark:border-emerald-900/60 dark:bg-emerald-950/30",
    text: "text-emerald-900 dark:text-emerald-300",
  },
  redact_first: {
    container: "border-amber-200/80 bg-[#f9f7f2] dark:border-amber-900/50 dark:bg-stone-900/40",
    text: "text-[#78541a] dark:text-amber-300",
  },
  do_not_upload: {
    container: "border-red-200 bg-red-50/80 dark:border-red-900/60 dark:bg-red-950/40",
    text: "text-red-900 dark:text-red-400",
  },
};

function buildVerdictReason(findings: ScanRecord["findings"]): string {
  const critical = findings.filter((f) => f.severity === "critical").length;
  const high = findings.filter((f) => f.severity === "high").length;
  const injections = findings.filter((f) => f.category === "prompt_injection").length;

  const parts: string[] = [];
  if (injections > 0)
    parts.push(`${injections} prompt-injection instruction${injections > 1 ? "s" : ""} removed`);
  if (critical > 0)
    parts.push(`${critical} critical-severity finding${critical > 1 ? "s" : ""}`);
  if (high > 0 && !critical)
    parts.push(`${high} high-severity finding${high > 1 ? "s" : ""}`);

  if (parts.length === 0 && findings.length > 0)
    return `${findings.length} item${findings.length > 1 ? "s" : ""} detected that may need review.`;
  if (parts.length === 0)
    return "No sensitive content detected in this document.";

  return parts.join("; ") + ".";
}

function buildMarkdownReport(scan: ScanRecord, destination: string): string {
  const date = new Date(scan.created_at).toLocaleString("en-IN", {
    day: "2-digit", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit",
  });

  const groupedFindings = new Map<string, number>();
  for (const f of scan.findings) {
    groupedFindings.set(f.category, (groupedFindings.get(f.category) ?? 0) + 1);
  }

  const findingLines = Array.from(groupedFindings.entries())
    .map(([cat, n]) => `- ${CATEGORY_LABELS[cat] ?? cat}: ${n}`)
    .join("\n");

  const verdictLabel = scan.verdict ? VERDICT_LABELS[scan.verdict] : "N/A";
  const aiSummary = scan.ai_analysis?.summary ?? "Not available";
  const actions = scan.ai_analysis?.recommended_actions?.length
    ? scan.ai_analysis.recommended_actions.map((a) => `- ${a}`).join("\n")
    : "- No specific actions recommended.";

  const safeText = scan.masked_text ?? "(Not available in this view)";

  return [
    `# PasteGuard Document Scan Report`,
    ``,
    `**Title:** ${scan.title ?? "Untitled"}`,
    `**Date:** ${date}`,
    `**Destination:** ${destination}`,
    `**Verdict:** ${verdictLabel}`,
    `**Risk score:** ${scan.risk_score} / 100 (${scan.risk_level})`,
    ``,
    `## Findings by category`,
    ``,
    findingLines || "No findings.",
    ``,
    `## AI review summary`,
    ``,
    aiSummary,
    ``,
    `## Recommended actions`,
    ``,
    actions,
    ``,
    `## Safe (masked) text`,
    ``,
    "```",
    safeText,
    "```",
    ``,
    `---`,
    `*Generated by PasteGuard. Raw text was never stored or transmitted.*`,
  ].join("\n");
}

export function RiskBadge({ level }: { level: string }) {
  return (
    <Badge
      variant="outline"
      className={cn(
        "font-medium capitalize text-xs border-0",
        RISK_COLORS[level] ?? "bg-neutral-100 text-neutral-600"
      )}
    >
      {level}
    </Badge>
  );
}

export function VerdictCard({ verdict, findings }: { verdict: Verdict; findings: ScanRecord["findings"] }) {
  const styles = VERDICT_STYLES[verdict];
  const label = VERDICT_LABELS[verdict];
  const reason = buildVerdictReason(findings);

  return (
    <div className={cn("rounded-xl border p-5 shadow-none", styles.container)}>
      <p className={cn("text-base font-semibold tracking-tight", styles.text)}>{label}</p>
      <p className="mt-1 text-xs leading-relaxed text-neutral-600 dark:text-neutral-400">{reason}</p>
    </div>
  );
}

export function ScanResultPanel({
  scan,
  destinationLabel,
}: {
  scan: ScanRecord;
  destinationLabel?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [reportDownloaded, setReportDownloaded] = useState(false);

  async function handleCopy() {
    if (!scan.masked_text) return;
    await navigator.clipboard.writeText(scan.masked_text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownloadRedacted() {
    if (!scan.masked_text) return;
    const blob = new Blob([scan.masked_text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const base = (scan.title ?? "scan").replace(/\.[^.]+$/, "");
    a.download = `${base}-redacted.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleDownloadReport() {
    const dest = destinationLabel ?? scan.destination;
    const md = buildMarkdownReport(scan, dest);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const base = (scan.title ?? "scan").replace(/\.[^.]+$/, "");
    a.download = `${base}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
    setReportDownloaded(true);
    setTimeout(() => setReportDownloaded(false), 2000);
  }

  const isAiOk = scan.ai_status === "ok" && !!scan.ai_analysis;
  const isFallback = scan.ai_status === "fallback";
  const isDocument = scan.source === "document";

  // Separate detector findings from AI findings
  const detectorFindings = scan.findings.filter((f) => f.source !== "ai");
  const aiFindings = scan.findings.filter((f) => f.source === "ai");

  // Group detector findings by category
  const groupedDetector = new Map<string, typeof detectorFindings>();
  for (const f of detectorFindings) {
    if (!groupedDetector.has(f.category)) groupedDetector.set(f.category, []);
    groupedDetector.get(f.category)!.push(f);
  }

  const fallbackNotice =
    scan.ai_notice ||
    "AI review is unavailable right now, so this result uses automatic detection only.";

  const severityOrder = ["critical", "high", "medium", "low"];

  return (
    <div className="mt-6 space-y-6 rounded-xl border border-neutral-200 bg-white p-6 shadow-none dark:border-neutral-800 dark:bg-neutral-900">
      {/* Truncation notice */}
      {scan.truncated && (
        <div className="rounded-lg border border-neutral-200 bg-neutral-50 px-4 py-3 text-xs text-neutral-600 dark:border-neutral-700 dark:bg-neutral-800/60 dark:text-neutral-400">
          Only the first 60,000 characters were scanned.
        </div>
      )}

      {/* Fallback Notice Banner */}
      {isFallback && (
        <div className="rounded-lg border border-neutral-200 bg-neutral-50 px-4 py-3 text-xs text-neutral-600 dark:border-neutral-700 dark:bg-neutral-800/60 dark:text-neutral-400">
          {fallbackNotice}
        </div>
      )}

      {/* Verdict card — prominent and calm */}
      {isDocument && scan.verdict && (
        <VerdictCard verdict={scan.verdict} findings={scan.findings} />
      )}

      {/* Risk Score: large number with a simple horizontal bar (tone only) */}
      <div className="space-y-3">
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-baseline gap-1.5">
            <span className="font-serif text-4xl font-bold tabular-nums text-neutral-900 dark:text-neutral-100">
              {scan.risk_score}
            </span>
            <span className="text-sm font-normal text-neutral-400">/100</span>
          </div>
          <RiskBadge level={scan.risk_level} />
          {scan.findings.length === 0 && (
            <span className="text-sm text-neutral-500">No sensitive data detected</span>
          )}
        </div>

        {/* Simple horizontal bar (tone only) */}
        <div className="h-2 w-full max-w-md overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800">
          <div
            className={cn(
              "h-full rounded-full transition-all duration-500",
              scan.risk_level === "low" && "bg-emerald-600 dark:bg-emerald-500",
              scan.risk_level === "medium" && "bg-amber-600 dark:bg-amber-500",
              scan.risk_level === "high" && "bg-orange-600 dark:bg-orange-500",
              scan.risk_level === "critical" && "bg-red-600 dark:bg-red-500"
            )}
            style={{ width: `${Math.min(100, Math.max(5, scan.risk_score))}%` }}
          />
        </div>

        {isAiOk && (
          <p className="text-xs text-neutral-500 dark:text-neutral-400">
            Reviewed by Gemini on masked text only
          </p>
        )}
      </div>

      {/* AI Contextual Review Section */}
      {isAiOk && scan.ai_analysis && (
        <div className="space-y-4 rounded-xl border border-neutral-200 bg-neutral-50/60 p-5 dark:border-neutral-800 dark:bg-neutral-800/30">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-200/80 pb-3 dark:border-neutral-700">
            <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
              AI Contextual Analysis
            </p>
            <span
              className={cn(
                "inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-medium border",
                scan.ai_analysis.safe_to_send
                  ? "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300"
                  : "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-300"
              )}
            >
              {scan.ai_analysis.safe_to_send ? "Safe to send" : "Not safe to send"}
            </span>
          </div>

          <p className="text-sm leading-relaxed text-neutral-800 dark:text-neutral-200">
            {scan.ai_analysis.summary}
          </p>

          {scan.ai_analysis.destination_assessment && (
            <div className="text-xs text-neutral-600 dark:text-neutral-400">
              <span className="font-semibold text-neutral-700 dark:text-neutral-300">
                Destination notes:{" "}
              </span>
              {scan.ai_analysis.destination_assessment}
            </div>
          )}

          {scan.ai_analysis.recommended_actions?.length > 0 && (
            <div className="space-y-1.5 pt-1">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
                Recommended Actions
              </p>
              <ul className="space-y-1 text-xs text-neutral-700 dark:text-neutral-300">
                {scan.ai_analysis.recommended_actions.map((act, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="mt-0.5 block h-1.5 w-1.5 shrink-0 rounded-full bg-[#2f5e3e]" />
                    <span>{act}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {aiFindings.length > 0 && (
            <div className="space-y-2 pt-2 border-t border-neutral-200/80 dark:border-neutral-700">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
                AI Detected Risks ({aiFindings.length})
              </p>
              <div className="space-y-2">
                {aiFindings.map((f) => (
                  <div
                    key={f.id}
                    className="rounded-lg border border-neutral-200 bg-white p-3 text-xs dark:border-neutral-700 dark:bg-neutral-900"
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono font-medium text-neutral-800 dark:text-neutral-200">
                        {f.placeholder}
                      </span>
                      <span className="capitalize text-neutral-500">{f.severity}</span>
                    </div>
                    {f.reason && (
                      <p className="mt-1 text-neutral-600 dark:text-neutral-400">
                        {f.reason}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Findings: tidy list with category, count and a severity badge */}
      {groupedDetector.size > 0 && (
        <div className="space-y-3">
          <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
            Detected Sensitive Data ({detectorFindings.length})
          </p>
          <ul className="divide-y divide-neutral-100 rounded-xl border border-neutral-200 bg-neutral-50/40 dark:divide-neutral-800 dark:border-neutral-800 dark:bg-neutral-900/40">
            {Array.from(groupedDetector.entries()).map(([cat, items]) => {
              const highestSeverity =
                items.reduce((prev, curr) => {
                  return severityOrder.indexOf(curr.severity) < severityOrder.indexOf(prev)
                    ? curr.severity
                    : prev;
                }, "low") || "low";

              return (
                <li key={cat} className="flex items-center justify-between px-4 py-3 text-sm">
                  <span className="font-medium text-neutral-800 dark:text-neutral-200">
                    {CATEGORY_LABELS[cat] ?? cat}
                  </span>
                  <div className="flex items-center gap-3">
                    <span
                      className={cn(
                        "inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium capitalize",
                        SEVERITY_COLORS[highestSeverity] ?? SEVERITY_COLORS.low
                      )}
                    >
                      {highestSeverity}
                    </span>
                    <span className="min-w-6 text-right font-mono text-xs font-semibold tabular-nums text-neutral-600 dark:text-neutral-300">
                      {items.length}
                    </span>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>
      )}

      {/* Masked Safe Text: Monospace box with Copy and Download buttons in its header */}
      {scan.masked_text !== undefined && (
        <div className="overflow-hidden rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-200 bg-neutral-50/80 px-4 py-2.5 dark:border-neutral-800 dark:bg-neutral-800/60">
            <span className="text-xs font-semibold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
              Safe Text
            </span>
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex min-h-[40px] items-center rounded-md border border-neutral-300 bg-white px-3.5 py-1.5 text-xs font-medium text-neutral-700 transition-colors hover:bg-neutral-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f5e3e] focus-visible:ring-offset-2 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:bg-neutral-800"
              >
                {copied ? "Copied" : "Copy safe text"}
              </button>
              <button
                type="button"
                onClick={handleDownloadRedacted}
                className="inline-flex min-h-[40px] items-center rounded-md border border-neutral-300 bg-white px-3.5 py-1.5 text-xs font-medium text-neutral-700 transition-colors hover:bg-neutral-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f5e3e] focus-visible:ring-offset-2 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:bg-neutral-800"
              >
                Download (.txt)
              </button>
              {isDocument && (
                <button
                  type="button"
                  onClick={handleDownloadReport}
                  className="inline-flex min-h-[40px] items-center rounded-md border border-neutral-300 bg-white px-3.5 py-1.5 text-xs font-medium text-neutral-700 transition-colors hover:bg-neutral-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f5e3e] focus-visible:ring-offset-2 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:bg-neutral-800"
                >
                  {reportDownloaded ? "Downloaded" : "Download report (.md)"}
                </button>
              )}
            </div>
          </div>
          <textarea
            readOnly
            value={scan.masked_text}
            rows={7}
            className="w-full resize-y border-0 bg-white p-4 font-mono text-xs leading-relaxed text-neutral-800 focus:outline-none dark:bg-neutral-900 dark:text-neutral-200"
          />
        </div>
      )}
    </div>
  );
}
